### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#1]
@tbeu @Andreas123456 @kvichans  It is new made, good ProjManager for Cud, maybe u want to test it, welcome
It is alpha

**Comment by kvichans** [comment]
1) Need accelerators for menu items. Variants: "Pro&ject manager", ... "&Config"

2) Troubles with create new proj. 
- Call `New project/ Open folder...` 
- Dlg `Select dir` is shown
- Into exist folder enter not exist name `try-pjm`
- see msg `Not exist file. Create?`

![pj-new1](https://cloud.githubusercontent.com/assets/7419630/16907874/d5ea3ad8-4ccf-11e6-8bdc-3484387150ea.PNG)
- Click to Yes
- See  `Uncorrect folder name`

![pj-new2](https://cloud.githubusercontent.com/assets/7419630/16907873/d5e83706-4ccf-11e6-9d9d-8af1f77c7d23.PNG)
- Return to `Select dir` dlg

3) Need to add all commands from local menu to `install.inf`. So user could assign hotkey for the cmds. And some cmds may be shown in global menu.

**Comment by Alexey-T** [comment]
@kvichans 1) Dont want accelerators (not looks good), 2) it is Cud issue- not PrjMan, 3) Added!!

**Comment by kvichans** [comment]
@Alexey-T 
1) Accelerators only help but do not trouble. Why they are not good? Users like me want accelerators.
2) Yes

**Comment by Alexey-T** [comment]
They may conflict with others (if 10-15 plugins will have accels)

**Comment by kvichans** [comment]
No conflicts! Accelerators work sequentially

**Comment by Alexey-T** [comment]
Also i dont add accel in my plugs.

**Comment by Alexey-T** [comment]
done accels.
