### ISSUE TITLE
Contx menu in ST has 2 modes: file/dir

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#13]
(Ftp items- ignore them)

2 modes of menu
![menu](https://cloud.githubusercontent.com/assets/4154978/16934322/2a08ee34-4d66-11e6-9eef-d2d2c7d19aa3.png)
![menu2](https://cloud.githubusercontent.com/assets/4154978/16934321/2a0760a0-4d66-11e6-9b8d-03f933b2fa80.png)

**Comment by Alexey-T** [comment]
Items very usefull, I can make new folders, rename
@pohmelie

**Comment by pohmelie** [comment]
@Alexey-T don't get about second screenshot. What should "Open containing folder" or "New file" should do for multiselection?

**Comment by Alexey-T** [comment]
It works for folder (if folder +file selected): new file in this folder, and "open shell window with folder"

**Comment by pohmelie** [comment]
@Alexey-T, but what if two directories selected?

**Comment by Alexey-T** [comment]
- new file
- rename
- ==
- new folder
- delete folder
- find in folder

This is menu for ONE folder (no files)
We dont need to look at other cases, need 1) one file 2) one folder

**Comment by pohmelie** [comment]
@Alexey-T take a look at commit, and especially at https://github.com/pohmelie/cuda_project_man/commit/7fead2cbb9c0ef518d78c8549260d008de298f94#diff-743b1adbf37db12e16e01ef62a6f7d72R308 since this is not implemented yet.

**Comment by Alexey-T** [comment]
I must see it
