### ISSUE TITLE
Suggest compact menu

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#31]
I suggest more small ctx menu with submenus

```
Project file >>>
    New project
    Open project...
    Recent projects >>>
    Save project as...
    -----
    Go to file...
    Project properties...
    Config...
Root nodes >>>
    Add directory...
    Add file...
    Clear project
    Remove node
Selected file >>>
(for dirs this section is: Selected directory >>>)
    Rename... (for file)
    Delete file (for file)
    Set as main file (for file)
-------
Refresh
```

It is more compact

**Comment by Alexey-T** [comment]
@pohmelie @kvichans : Do u agree?

**Comment by kvichans** [comment]
I dont agree. 
I wish **all** PrMan commands in ctx-menu with Project file. So no need to open menu Plugins--PrMan.

**Comment by Alexey-T** [comment]
Added

```
    Go to file...
    Project properties...
    Config...
```

to above, not sure need to add more.

**Comment by kvichans** [comment]
I think u need to pass this config to user level. Lets anybody to config menu for self.

**Comment by kvichans** [comment]
Dont need GUI to config ctx menus. Config file is good way. 
U give the file with full lists for all node types. A user only comments some rows to configure.

**Comment by pohmelie** [comment]
Agree with @kvichans, some default config with ability to redefine. Don't really know is this «cuda-way» or not. If no plugin provide same way to change context menu, than this should be abandoned. Or promoted and all other plugins should have this ability.

**Comment by Alexey-T** [comment]
Config Menu plg provides a way to config top menu via settings/*.json.  Can you make .json (maybe default file in plg dir, and copy in settings/)

**Comment by pohmelie** [comment]
If it was for me, than not earlier, than in four days.

**Comment by Alexey-T** [comment]
Okay, in 4 days ok

**Comment by Alexey-T** [comment]
Okey, i did it as i wanted//no config, i dont need it, IMO config is easy to break, if user makes typo in actionname
