### ISSUE TITLE
(request) New cmd to find current file in proj-tree

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#35]
Нужна команда "Синхронизовать", которая будет устанавливать текущий узел в дереве Проект по активному файлу.
Речь именно о команде, а не о режиме "Поддерживать синхронизацию". Необходимость такого режима - отдельная тема.

**Comment by Alexey-T** [comment]
done: test pls.

**Comment by kvichans** [comment]
Не все хорошо.
Если файл в табе не входит в Дерево Проекта, то сообщение в статусе нужно давать другое

**Comment by Alexey-T** [comment]
поправил- лучше?

**Comment by kvichans** [comment]
Норм
