### ISSUE TITLE
Linux: dir X11 included into itself

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#44]
each unfolding shows x11 inside x11.
same files each level.
![lin-reccc](https://user-images.githubusercontent.com/4154978/27258983-1dec091c-5411-11e7-8161-d71a2a400593.png)

@pohmelie

**Comment by pohmelie** [comment]
`/usr/bin/X11` is symlink

**Comment by Alexey-T** [comment]
Ok, confirm it. tks.
