### ISSUE TITLE
commd "Go to file" was broken, made some workaround

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#49]
I added unfolding

        #workaround: unfold all tree, coz tree loading is lazy
        #todo: dont unfold all, but allow enum_all() to work
        tree_proc(self.tree, TREE_ITEM_UNFOLD_DEEP, 0)

it didnt work, coz tree loading is lazy, and enum_all() sees all tree nodes.
This workaround is not good. what to do?
@pohmelie

**Comment by pohmelie** [comment]
The problem is unclear to me. "Go to file"? What is it. Since loading is lazy, there is no way to know files deeper. We can go back to eager loading.

**Comment by Alexey-T** [comment]
Go to file is command in projman context menu. It walks for all items. It stops when file name found.
Maybe- Need Python method, which I can call in gotofile. This method must load all tree content-- ignoring lazy.

**Comment by pohmelie** [comment]
Project have more than one root, so you need `pathlib.Path.glob` method. And also reveal the tree in right node. Sounds not very good.

**Comment by Alexey-T** [comment]
Hm?? Can you write method? Which loads all nodes filnames in tree, without unfolding all

**Comment by pohmelie** [comment]
The problem is that lazy unfolding was done as method to remove latency. If we will return eager path loading, then this will be slow.

**Comment by Alexey-T** [comment]
yes; so I suggest to return eager only for one case: when I call method "preload_all()".

**Comment by Alexey-T** [comment]
2nd way: GoToFile method must not call enum_all()
It must find node by analizing path.

**Comment by pohmelie** [comment]
Both ways are good enough, in case of `preload_all` we will get «free» full tree. But, this will cause bugs (I don't really know which one right now, but I think it will). Second way is more isolated, so less problems will occur.
