### ISSUE TITLE
How to get "main file" path from other plugin?

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#51]
I open my file with ext `cuda-proj` and see in side panel a tree
![default](https://user-images.githubusercontent.com/7419630/42314361-837573f4-804d-11e8-9db9-243fe317e8fd.png)

I want to get path to main project file and try 
```python
import cuda_project_man
proj_vars   = cuda_project_man.project_variables()
proj_path   = proj_vars.get('ProjMainFile', '')
print('proj_path=',proj_path)
print('proj_vars=',proj_vars)
print('global_project_info=',cuda_project_man.global_project_info)
```
but see 
`proj_path=`
`proj_vars= OrderedDict([('ProjDir', ''), ('ProjMainFile', ''), ('ProjMainFileNameOnly', ''), ('ProjMainFileNameNoExt', '')])`
`global_project_info= {'nodes': [], 'filename': '', 'vars': [], 'mainfile': ''}`

What is the right way?

**Comment by Alexey-T** [comment]
it is right. but user must right-click on Proj panel file, and call item "Set as main file". then MainFile is set.

**Comment by Alexey-T** [comment]
a- update ProjectMan plugin (if not)
b- i see after "Set as main file":
```
>>> =cuda_project_man.global_project_info
{'filename': '', 'nodes': ['/home/user/cuda/attabs/demo_lazarus'], 'vars': [], 'mainfile': '/home/user/cuda/attabs/demo_lazarus/Demo.lpi'}
```

**Comment by kvichans** [comment]
Версия ПрМана совпадает с той что в Куд 1.57
Чем мне поможет что у вас хорошо?

**Comment by Alexey-T** [comment]
не знаю. может из-за Вин? не могу проверить вин, на даче.

**Comment by Alexey-T** [comment]
кстати, ваш ExtTools читает переменные. было все ок.

**Comment by kvichans** [comment]
У меня не читает

**Comment by Alexey-T** [comment]
кажется плагин старый. нет иконок на тулбаре и надписи  Project

**Comment by kvichans** [comment]
Возможно. 
В дистро 1.57 у этого плага вообще нет подпапки icons. Но все *.py и install.inf совпадают с моими.
Обновить из ГХ?

**Comment by kvichans** [comment]
Иконки нашлись в папке data\projtoolbaricons\
![default](https://user-images.githubusercontent.com/7419630/42320076-b59953b4-805c-11e8-8c31-33cd80cc3b6b.png)

**Comment by kvichans** [comment]
Обновил из ГХ
Проблема осталась

**Comment by kvichans** [comment]
Появилось стабильное сообщение при запуске Куд
`Incorrect filetype icon: C:\Programs\CudaText\data\filetypeicons\vscode_16x16\icon_bad.png`

**Comment by Alexey-T** [comment]
может вам надо эту папку иконок обновить из дистро?

**Comment by kvichans** [comment]
Файл с этой иконкой уже из дистро.
Похоже сообщение от ПроджМана, так как если я удаляю его install.inf то сообщение исчезает

**Comment by Alexey-T** [comment]
не вижу ошибку с icon_bad.png. это крестик для залоченных файлов.
