### ISSUE TITLE
How to use cuda_project_man in FindInFiles4?

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#53]
[ru: How..?](https://github.com/Alexey-T/CudaText/issues/2522)

Is it true that Project is 
- set of **folders** (with subfolders) and some **files**,
- **filter** (set of masks) to ignore files in [sub-]folders.

**How to use the plugin in FindInFiles4 (FF4)?**

(0) **How to check** that project is loaded?
(1) **How to get** set/filter?
(2) I suggest a way to use project in FF4:
  - Project folders will be roots for search (FF4 allows many roots in field From)
  - Folders of project files also will be roots.
  - Project filter is added into field **Ex**.

Example
Consider project
```Python
{    "nodes": [
        "C:\\path_one\\folder1",
        "C:\\path_one\\folder2",
        "C:\\path_two\\file1.ext",
        "C:\\path_two\\file2.ext",
]}
```
with filter `*.git *.exe`
Search with options
![image](https://user-images.githubusercontent.com/7419630/80975355-aa96c680-8e2a-11ea-937e-ddd0b3920a2c.png)
is equal to
![image](https://user-images.githubusercontent.com/7419630/80975545-e2057300-8e2a-11ea-8223-8f8e48324e45.png)

Is my idea good?

**Comment by pohmelie** [comment]
> Is it true that Project is

Looks like "yes".

> How to check that project is loaded?

I hope this is useful https://github.com/pohmelie/cuda_project_man/blob/master/__init__.py#L18

> How to get set/filter?

Looks like `MASKS_IGNORE` is what you want https://github.com/pohmelie/cuda_project_man/blob/master/__init__.py#L690

> Is my idea good?

I have no context about FF4 and do not know what it goals.

**Comment by kvichans** [comment]
@pohmelie Don't worry about FF4. 

Sorry, i don't understand your refs.
Could you show me code for another plugin **how to** "check loaded project" and "get set"/"get filter" from the project?

```python
import cuda_project_man
???
```

**Comment by pohmelie** [comment]
I have no idea how all system works behind single plugin. I've just inspected source code and saw some useful points. Looks like `MASKS_IGNORE` and `project_variables` are reachable from non-plugin code. I don't know how to interact between plugins.
