### ISSUE TITLE
button 'add folder' on toolbar doesnt work under Python 3.4 (Wine)

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#54]
почему-то кнопка ничего не делает. креша нет тоже.
папка в проект не добавляется после выбора ее в диалоге.

@pohmelie @olehl почему так?

pathlib не может быть причиной?
 [Search domain realpython.com/python-pathlib/] https://realpython.com/python-pathlib/
The pathlib module was introduced in Python 3.4 (PEP 428) to deal with these challenges.

**Comment by pohmelie** [comment]
Если трейсбеков нет, значит `dlg_dir("")` возвращает `None`

**Comment by Alexey-T** [comment]
нет, добавил в add_node() принт значение path,
и оно вывело path!

add_node: C:\users\user\My Documents\tst-aencoding

**Comment by pohmelie** [comment]
Там же дальше ещё одна проверка https://github.com/pohmelie/cuda_project_man/blob/master/__init__.py#L341

**Comment by Alexey-T** [comment]
во все  if добавил print и оно печатает. в add_node. но дерево не отображает нового.

**Comment by Alexey-T** [comment]
cuda_testing_dlg_proc работает с деревом в Пи 34.
дело не в tree_proc

![Screenshot from 2021-01-13 17-10-59](https://user-images.githubusercontent.com/4154978/104463128-6c10f880-55c2-11eb-951a-f52aed2e8334.png)

**Comment by pohmelie** [comment]
Ну если все питоновские методы вызываются, то надо смотреть на уровне cuda.

**Comment by Alexey-T** [comment]
96% что питон код как-то не отрабатывает.

**Comment by pohmelie** [comment]
Можешь трейсы до вызовов работы с деревом сделать и проверить вызываются ли они.

**Comment by Alexey-T** [comment]
добавил принты- 3 шт на все 3 вызова TREE_ITEM_ADD.
[__init__.zip](https://github.com/pohmelie/cuda_project_man/files/5809586/__init__.zip)

В Пи38 так при "добавить файл"
```
Python 3.8
Startup: 240ms, plugins: 0ms ()
Init: cuda_project_man
tree add1
Init: cudatext
add_node: /home/user/cuda/cuda/app/py/cuda_addonman/install.inf
tree add1
tree add2
tree add3
refresh..
Init: cuda_hilite_occurrences
```

в Пи34 плохо
```
Python 3.4
Loaded session: "history session.json", 10ms, 0 file(s) + 1 modified
Startup: 290ms, plugins: 0ms ()
Init: cuda_project_man
tree add1
add_node: Z:\home\user\auto cmt1.c
tree add1
refresh..
```

**Comment by Alexey-T** [comment]
падает внутри def is_hidden!!
и идет в except.
```
Traceback (most recent call last):
  File "Z:\home\user\cudatext_build\win32\py\cuda_project_man\__init__.py", line 604, in action_add_file
    self.add_node(lambda: dlg_file(True, "", "", ""))
  File "Z:\home\user\cudatext_build\win32\py\cuda_project_man\__init__.py", line 345, in add_node
    self.action_refresh()
  File "Z:\home\user\cudatext_build\win32\py\cuda_project_man\__init__.py", line 517, in action_refresh
    elif self.options.get("no_hidden", True) and is_hidden(spath):
  File "Z:\home\user\cudatext_build\win32\py\cuda_project_man\__init__.py", line 80, in is_hidden
    return bool(os.stat(s).st_file_attributes & stat.FILE_ATTRIBUTE_HIDDEN)
AttributeError: 'os.stat_result' object has no attribute 'st_file_attributes'
```

**Comment by Alexey-T** [comment]
о!!!

On Windows, the following file attribute constants are available for use when testing bits in the st_file_attributes member returned by os.stat(). See the Windows API documentation for more detail on the meaning of these constants.

stat.FILE_ATTRIBUTE_ARCHIVE
stat.FILE_ATTRIBUTE_COMPRESSED
stat.FILE_ATTRIBUTE_DEVICE
stat.FILE_ATTRIBUTE_DIRECTORY
stat.FILE_ATTRIBUTE_ENCRYPTED
stat.FILE_ATTRIBUTE_HIDDEN
stat.FILE_ATTRIBUTE_INTEGRITY_STREAM
stat.FILE_ATTRIBUTE_NORMAL
stat.FILE_ATTRIBUTE_NOT_CONTENT_INDEXED
stat.FILE_ATTRIBUTE_NO_SCRUB_DATA
stat.FILE_ATTRIBUTE_OFFLINE
stat.FILE_ATTRIBUTE_READONLY
stat.FILE_ATTRIBUTE_REPARSE_POINT
stat.FILE_ATTRIBUTE_SPARSE_FILE
stat.FILE_ATTRIBUTE_SYSTEM
stat.FILE_ATTRIBUTE_TEMPORARY
stat.FILE_ATTRIBUTE_VIRTUAL

    New in version 3.5.

**Comment by pohmelie** [comment]
Ну, хорошо что нашлось.
