### ISSUE TITLE
What is the best way to add stuff to project's 'vars' from other plugins

### ISSUE THREAD

**Issue by halfbrained** [pohmelie/cuda_project_man#56]
Is just modifying `p.global_project_info['vars']`, and then calling `action_save_project_as` like this ok?
``` python
proj_fn = p.global_project_info.get('filename')
app_proc(PROC_EXEC_PLUGIN, 'cuda_project_man,action_save_project_as,'+proj_fn)
```

**Comment by Alexey-T** [comment]
I didn't try that, sorry. IDK. need to try and check it.

**Comment by halfbrained** [comment]
It works, but I'm not sure if the save method `action_save_project_as` might change.

**Comment by halfbrained** [comment]
I'll close the issue later if no better option presents itself :)

**Comment by Alexey-T** [comment]
I didn't test to save the proj via that method. can you test it?

**Comment by halfbrained** [comment]
I did - it works

**Comment by Alexey-T** [comment]
I 'll try not to break that method.
