### ISSUE TITLE
(request) Icons for nodes and folders

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#8]
Now all nodes and all folder in nodes have same icons. But command `Remove node` isnt applyed to selected folder.
Need different icons.

**Comment by Alexey-T** [comment]
It is applied to root-node for sel folder.

**Comment by kvichans** [comment]
Yes - i tryed the cmd over folder and node was removed.
@Alexey-T Do u agree with "Need different icons"?

**Comment by Alexey-T** [comment]
icons needed for png/jpg/gif/css/html files. Not agree- not for nodes.

**Comment by kvichans** [comment]
I see 3 types of icons
![pj-tree1](https://cloud.githubusercontent.com/assets/7419630/16911472/58ec207e-4ce7-11e6-9419-11db4ef6932f.PNG)
and 4 types of items: project, node, folder, file.
One icon for node and for folder is bad.

**Comment by Alexey-T** [comment]
@pohmelie What do u think

**Comment by pohmelie** [comment]
@Alexey-T, @kvichans, don't think we need four type of icons. Since node is virtual item and if there will be one icon for nodes how will node-file and node-directory differ?

**Comment by kvichans** [comment]
@pohmelie `cuda_text` and `bk` in pic have same icon. But they have diff sense
- `cuda_text` is project _node_
- `bk` is simple folder

Are u agree?

**Comment by Alexey-T** [comment]
IMO 2 more icons (node file, node dir) arenot needed, node file is OK as file, node dir is ok as dir

**Comment by pohmelie** [comment]
@kvichans, `cuda_ext` is simple folder too. Nothing special about nodes it's just root items.

**Comment by kvichans** [comment]
@pohmelie Why cmd "Remove node" acts only to root items? For the cmd these nodes are _special_. Agree?

**Comment by pohmelie** [comment]
@kvichans 

> Why cmd "Remove node" acts only to root items?

Cause @Alexey-T said to do such behaviour.

> For the cmd these nodes are special

"Remove node" acts node. Node is whole subtree. It's not just remove top. So, top node same _special_ as bottom node is.

**Comment by kvichans** [comment]
OK
Let's cmd named "Remove whole branch". _Node_ confuses.
