### ISSUE TITLE
(request) Exclude some files/folders from node

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#9]
Will be good to have three level settings for exluding 
- **Plugin level**: mask for files and mask for folders. Now plugin has list of extansions - it's better than nothing.
- **Project level**: as `.gitignore`
- **Command level**: cmd to exclude any subitem

**Comment by Alexey-T** [comment]
What is it? `Project level: as .gitignore`, what file, in where?

**Comment by kvichans** [comment]
IMHO In future each Proj will have more properties - now i see only "nodes" in *.cuda-proj. Exclude-masks are well will be here.

**Comment by Alexey-T** [comment]
Yes exc-mask will be here
